import fs from 'node:fs';import assert from 'node:assert/strict';
const engines=await import(process.env.PLAYWRIGHT_MODULE||'@playwright/test');const engine=process.env.BROWSER||'chromium';const browser=await engines[engine].launch({args:engine==='chromium'?['--no-sandbox']:[]});const rows=[];
for(const site of JSON.parse(fs.readFileSync('.verification/matrix.json')).filter(s=>s.name!=='wp51'&&(!process.env.SITE||s.name===process.env.SITE))){
 const ctx=await browser.newContext({storageState:'.verification/'+site.name+'-auth.json',viewport:{width:1440,height:1100}});const p=await ctx.newPage();const r={site:site.name,browser:engine};
 try{
 console.log(site.name,'OPEN');await p.goto('http://localhost:'+site.port+'/wp-admin/post-new.php');console.log('LOADED');await p.waitForFunction(()=>window.wp?.data?.dispatch('core/block-editor'));const close=p.locator('.components-modal__frame').getByRole('button',{name:/Close/});if(await close.count())await close.first().click();
 await p.waitForFunction(()=>window.wp?.data?.select('core/editor')?.getCurrentPostId());await p.evaluate(()=>{wp.data.dispatch('core/editor').editPost({title:'標準フォントの保存検証',status:'publish'});wp.data.dispatch('core/block-editor').resetBlocks([wp.blocks.createBlock('core/paragraph',{content:'標準段落 <strong>太字</strong> <a href="https://example.com">リンク</a><br>日本語 ABC 123'}),wp.blocks.createBlock('core/heading',{content:'日本語の見出し'}),wp.blocks.createBlock('core/buttons',{},[wp.blocks.createBlock('core/button',{text:'日本語ボタン'})])])});
 console.log('FIXTURE');r.blocks=[];
 for(const name of ['core/paragraph','core/heading','core/button']){console.log(name);
 await p.evaluate(name=>{const s=wp.data.select('core/block-editor');const all=s.getBlocks().flatMap(b=>[b,...b.innerBlocks]);wp.data.dispatch('core/block-editor').selectBlock(all.find(b=>b.name===name).clientId)},name);
 await p.waitForTimeout(300);const tab=p.getByRole('tab',{name:'Block',exact:true});if(await tab.count())await tab.click();
 const styles=p.getByRole('tab',{name:'Styles',exact:true});if(await styles.count())await styles.click();console.log('INSPECTOR',name);const opts=p.getByRole('button',{name:'Typography options',exact:true});await opts.waitFor({state:'visible'});if(await opts.count()){await opts.click();const toggle=p.getByRole('menuitemcheckbox',{name:/^(Show )?Font( family)?$/i});if(await toggle.count()&&await toggle.getAttribute('aria-checked')==='false')await toggle.click();await p.keyboard.press('Escape');}
 console.log('CONTROL',name);let font=p.getByRole('combobox',{name:/Font( family)?$/i});if(!await font.count())font=p.locator('select').filter({has:p.locator('option[value="tinyjpfont-huifont"]')});
 if(!await font.count())throw new Error('No standard font control: '+(await p.locator('body').innerText()).slice(-2200));
 const el=font.first();if(await el.evaluate(e=>e.tagName)==='SELECT')await el.selectOption({label:'ふい字'});else{await el.click();await p.getByRole('option',{name:'ふい字',exact:true}).click();}
 r.blocks.push(await p.evaluate(()=>{const b=wp.data.select('core/block-editor').getSelectedBlock();return {name:b.name,font:b.attributes.fontFamily}}));assert.equal(r.blocks.at(-1).font,'tinyjpfont-huifont');
 }
 console.log('SAVE');await p.evaluate(async()=>await wp.data.dispatch('core/editor').savePost());console.log('SAVED');r.postId=await p.evaluate(()=>wp.data.select('core/editor').getCurrentPostId());await p.reload();await p.waitForFunction(()=>window.wp?.data?.select('core/editor')?.getEditedPostContent()?.includes('tinyjpfont-huifont'));r.saved=await p.evaluate(()=>wp.data.select('core/editor').getEditedPostContent());assert.ok(r.saved.includes('<strong>太字</strong>'));assert.ok(r.saved.includes('<br>'));
 let frame;for(let attempt=0;attempt<100;attempt++){frame=p.frames().find(f=>f.url().startsWith('blob:'))||p.mainFrame();if(await frame.locator('[data-type="core/paragraph"]').count())break;await p.waitForTimeout(200);}await frame.locator('[data-type="core/paragraph"]').first().waitFor({state:'visible'});await frame.evaluate(async()=>await document.fonts.load('24px Huifont','日本語'));await p.screenshot({path:'.verification/results/'+site.name+'-'+engine+'-standard-editor.png'});
 await p.goto('http://localhost:'+site.port+'/?p='+r.postId);r.loaded=await p.evaluate(async()=>{const f=await document.fonts.load('24px Huifont','日本語');return f.length>0&&f.every(x=>x.status==='loaded')});assert.ok(r.loaded);r.families=await p.locator('.has-tinyjpfont-huifont-font-family').evaluateAll(es=>es.map(e=>getComputedStyle(e).fontFamily));assert.ok(r.families.length>=3&&r.families.every(x=>x.includes('Huifont')));await p.screenshot({path:'.verification/results/'+site.name+'-'+engine+'-standard-public.png'});r.result='PASS';
 }catch(e){r.result='FAIL';r.error=e.stack;await p.screenshot({path:'.verification/results/'+site.name+'-'+engine+'-standard-fail.png'}).catch(()=>{})}
 console.log(site.name,r.result,r.error?.split('\n')[0]||'');rows.push(r);fs.writeFileSync('.verification/results/modern-'+engine+(process.env.SITE?'-'+process.env.SITE:'')+'.json',JSON.stringify(rows,null,2));await ctx.close();
}
await browser.close();if(rows.some(x=>x.result==='FAIL'))process.exitCode=1;
