import fs from 'node:fs';import assert from 'node:assert/strict';const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'@playwright/test');const b=await chromium.launch({args:['--no-sandbox']});const rows=[];
for(const site of JSON.parse(fs.readFileSync('.verification/matrix.json')).filter(s=>!process.env.SITE||s.name===process.env.SITE)){
 const ctx=await b.newContext({storageState:'.verification/'+site.name+'-auth.json',viewport:{width:1440,height:1100}});const p=await ctx.newPage();let r={site:site.name};try{
 await p.goto('http://localhost:'+site.port+'/wp-admin/post-new.php');await p.waitForFunction(()=>window.wp?.data?.select('core/editor')?.getCurrentPostId());const close=p.locator('.components-modal__frame').getByRole('button',{name:/Close/});if(await close.count())await close.first().click();const tips=p.getByRole('button',{name:/Disable tips|Dismiss tip/});if(await tips.count())await tips.first().click();
 await p.evaluate(()=>{const d=wp.data.dispatch('core/block-editor')||wp.data.dispatch('core/editor');wp.data.dispatch('core/editor').editPost({title:'任意の標準段落変換',status:'publish'});const block=wp.blocks.createBlock('tinyjpfont/huiji',{textString:'日本語 <strong>太字</strong> <a href="https://example.com">リンク</a><br>改行 ABC'});d.resetBlocks([block]);d.selectBlock(block.clientId)});
 if(site.name==='wp71')await p.getByRole('button',{name:'ふい字',exact:true}).first().click();else await p.locator('.block-editor-block-switcher__toggle,.editor-block-switcher__toggle').first().click();const choice=p.getByRole('menuitem',{name:/Paragraph/});if(await choice.count())await choice.first().click();else await p.getByRole('button',{name:'Paragraph',exact:true}).click();
 r.block=await p.evaluate(()=>(wp.data.select('core/block-editor')||wp.data.select('core/editor')).getBlocks()[0]);assert.equal(r.block.name,'core/paragraph');assert.ok(r.block.attributes.content.includes('<strong>太字</strong>'));assert.ok(r.block.attributes.content.includes('<br>'));assert.ok(r.block.attributes.fontFamily==='tinyjpfont-huifont'||r.block.attributes.content.includes('Huifont'));
 await p.evaluate(async()=>await wp.data.dispatch('core/editor').savePost());r.id=await p.evaluate(()=>wp.data.select('core/editor').getCurrentPostId());await p.reload();await p.waitForFunction(()=>window.wp?.data?.select('core/editor')?.getEditedPostContent()?.includes('core/paragraph')||window.wp?.data?.select('core/editor')?.getEditedPostContent()?.includes('wp:paragraph'));r.saved=await p.evaluate(()=>wp.data.select('core/editor').getEditedPostContent());assert.ok(r.saved.includes('<strong>太字</strong>'));assert.ok(!r.saved.includes('wp:tinyjpfont/huiji'));
 await p.goto('http://localhost:'+site.port+'/?p='+r.id);assert.ok(await p.evaluate(async()=>{const f=await document.fonts.load('24px Huifont','日本語');return f.length>0}));await p.screenshot({path:'.verification/results/'+site.name+'-transform.png'});delete r.block.clientId;r.result='PASS';
 }catch(e){r.result='FAIL';r.error=e.stack;await p.screenshot({path:'.verification/results/'+site.name+'-transform-fail.png'}).catch(()=>{})}
 rows.push(r);console.log(site.name,r.result,r.error?.split('\n')[0]||'');fs.writeFileSync('.verification/results/transform'+(process.env.SITE?'-'+process.env.SITE:'')+'.json',JSON.stringify(rows,null,2));await ctx.close();
}await b.close();if(rows.some(r=>r.result==='FAIL'))process.exitCode=1;
