from pathlib import Path
import json
root=Path(__file__).resolve().parent.parent
fonts=json.loads((root/'assets/fonts.json').read_text())
css='/* Generated by tools/generate-css.py. Font files are fetched only when used. */\n'
for f in fonts:
 css+='@font-face{font-family:"'+f['family']+'";font-style:normal;font-weight:'+str(f['weight'])+';font-display:swap;src:url("'+f['url']+'") format("'+f['format']+'");}\n'
for family,selectors in [('Noto Sans Japanese','.noto,.tinyjpfont_noto,.wp-block-tinyjpfont-noto'),('Huifont','.huiji,.tinyjpfont_huiji,.wp-block-tinyjpfont-huiji'),('honokamaru','.honokamaru')]:
 css+=selectors+'{font-family:"'+family+'",sans-serif;}\n'
for f in fonts:css+='.has-tinyjpfont-'+f['id']+'-font-family{font-family:"'+f['family']+'",sans-serif !important;}\n'
for file in ['addfont.css','addfont_lite.css']:(root/file).write_text(css)
